name: "PlotPlug"
version: "1.0"
description: "An easy to use plot plugin."
author: "mttprvst13"
main: me.mttprvst13.plotMain
load: STARTUP
commands:
    getplot:
        description: Gets the plot that your currently in.
    plot:
        description: The default plot command.